version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - cd client
      - pwd
      - npm install -g typescript
      - npm install -g vite
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  base-directory: 'dist'
  files:
    - '**/*'